export enum ROUTE_APP {
  ADMINISTRATOR = 'administrator',
  AUTH_LOGIN = '/auth/login',
  DASHBOARD = 'dashboard',
  LOGIN = 'login',
  AGENT = 'agent',
  PROSPECT = 'prospect',
  CUSTOMER = 'customer',
  ADD_CUSTOMERS = 'add-customers',
  ALL_CUSTOMERS = 'all-customers',
  ADD_AGENTS = 'add-agents',
  ALL_AGENTS = 'all-agents',
  ADD_PROSPECTS = 'add-prospects',
  ALL_PROSPECTS = 'all-prospects',
  EDIT_CUSTOMERS = 'edit-customers',
  ADD_POLICY = 'add-policy',
  ALL_POLICY = 'all-policy',
  POLICY = 'policy',
  SEARCH = 'search',
  SEARCHES = 'searches',
}
